### ISSUE TITLE
Upgrade to latest version of twitter-cldr-js

### ISSUE THREAD

**Issue by sarchila** [twitter/twitter-cldr-npm#6]
Wondering if this package could be updated to use the latest twitter-cldr-js. I'm hoping to use the 'ordinal plurals' functionality that was introduced in twitter-cldr-js 2.4.0.  Thanks

**Comment by caniszczyk** [comment]
@sarchila feel free to send a pull request, that always moves things faster :)

**Comment by KL-7** [comment]
I'm about to publish a new version. 

Keep in mind that 2.4.0 adds Unicode regex support which significantly increases the bundle size (from ~110Kb to ~280Kb for minified version). We have plans for modularizing the library so you can load only what you need, but it's not something we can offer just yet.

**Comment by KL-7** [comment]
@sarchila I just pushed [v1.4.0](https://www.npmjs.com/package/twitter_cldr) that is based on twitter-cldr-js v2.4.0. Let me know how it works for you.

**Comment by sarchila** [comment]
Wow, thanks for being so quick and responsive.  I'm going to check it out soon!  :+1:
